ARG DEBIAN_FRONTEND=noninteractiveFROM ubuntu
RUN apt-get update
RUN apt-get -y install apache2
ADD . /var/www/html
ENTRYPOINT apachectl -D FOREGROUND
ENV name Intellipaat
ARG DEBIAN_FRONTEND=noninteractive
